// Code generated by Kitex v0.13.1. DO NOT EDIT.

package recommendservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	recommend "video_douyin/kitex_gen/recommend"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetFeed(ctx context.Context, req *recommend.GetFeedRequest, callOptions ...callopt.Option) (r *recommend.GetFeedResponse, err error)
	UpdateUserProfile(ctx context.Context, req *recommend.UpdateUserProfileRequest, callOptions ...callopt.Option) (r *recommend.UpdateUserProfileResponse, err error)
	GetUserInterests(ctx context.Context, req *recommend.GetUserInterestsRequest, callOptions ...callopt.Option) (r *recommend.GetUserInterestsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRecommendServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRecommendServiceClient struct {
	*kClient
}

func (p *kRecommendServiceClient) GetFeed(ctx context.Context, req *recommend.GetFeedRequest, callOptions ...callopt.Option) (r *recommend.GetFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFeed(ctx, req)
}

func (p *kRecommendServiceClient) UpdateUserProfile(ctx context.Context, req *recommend.UpdateUserProfileRequest, callOptions ...callopt.Option) (r *recommend.UpdateUserProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserProfile(ctx, req)
}

func (p *kRecommendServiceClient) GetUserInterests(ctx context.Context, req *recommend.GetUserInterestsRequest, callOptions ...callopt.Option) (r *recommend.GetUserInterestsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInterests(ctx, req)
}
