// Code generated by Kitex v0.13.1. DO NOT EDIT.

package feedservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	feed "video_douyin/kitex_gen/feed"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetFeed(ctx context.Context, req *feed.FeedRequest, callOptions ...callopt.Option) (r *feed.FeedResponse, err error)
	GetVideoChunk(ctx context.Context, req *feed.ChunkRequest, callOptions ...callopt.Option) (r *feed.ChunkResponse, err error)
	PreloadVideo(ctx context.Context, req *feed.PreloadRequest, callOptions ...callopt.Option) (r *feed.PreloadResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kFeedServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFeedServiceClient struct {
	*kClient
}

func (p *kFeedServiceClient) GetFeed(ctx context.Context, req *feed.FeedRequest, callOptions ...callopt.Option) (r *feed.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFeed(ctx, req)
}

func (p *kFeedServiceClient) GetVideoChunk(ctx context.Context, req *feed.ChunkRequest, callOptions ...callopt.Option) (r *feed.ChunkResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoChunk(ctx, req)
}

func (p *kFeedServiceClient) PreloadVideo(ctx context.Context, req *feed.PreloadRequest, callOptions ...callopt.Option) (r *feed.PreloadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreloadVideo(ctx, req)
}
